version: '3.8'

services:
  api:
    container_name: api_container
    build: ./app
    restart: unless-stopped
    command:
      bash -c 'uvicorn app.api:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - .:/usr/src/app/
    ports:
      - 8081:8000
